package com.tocaboca.tocalifeworldd.edfrgtr

object KOfrkorfkorgtgt {
    var gtitghugt: String = "link"
    var nhyjiohyiohy5: String = "apps"
    var hy62ujj9: String? = "main_id"
    val rjgtjogtjjgtjtgjjgt = "tdb2"
    val gtgthtghgthugt: String = "country"
    val codeCodegtgt: String = "uff"
    val onegtgt = "deviceID="
    val vbfbbrfgfrggrffr = "sub_id_1="
    val vfbhbfryurfgrfrf = "ad_id="
    val gthgthugtuugthugt = "sub_id_4="
    val vbfbfrrfhrfhfrhfrfr = "sub_id_5="
    val ghyhy9555 = "sub_id_6="
    val gthyhjyhyjuuj = "naming"
    val trolologttggt = "deeporg"
    const val ju26ju26ju26ik = "47e0f0c3-9c68-4d02-9963-095b75dfb528"
    val g2huj2uj6uj = "92248770729033306185"
    val u2k2ik2ik2 = "com.tocaboca.tocalifeworldd"
    val gtjjgtjgtjgtjt = "r4dG4fFgGkSDjRYRKiQuTT"
    val ju26ju26j: String = "myID"
    var instIdgttg: String? = "instID"
    var ju26ju26uj2: String = "link"
}